#!/bin/sh
program=../stage_weblog
if [ ! -d actual_results ]; then
	mkdir actual_results
fi

function run_test {
	echo -n "$1......"
	./$1 $program
	if [ $? != 0 ]; then
		echo "failed"
		exit 1
	else
		echo "passed"
	fi
	}

rm actual_results/*

tests="test001 test002 test003 test004 test005 test006 test007 test008\
 test009 test010 test011 test012 test013 test014 test015 test016 test017 test018"

for test in $tests
do	
	run_test $test
done
