#!/bin/sh

test=$(basename $0)
test_source_dir=$(dirname $0)

echo -n "attempt to create database table when table already exists......"
$1 $test_source_dir/source_data/sample_log_file $test_source_dir/source_data/test006.sqlite > actual_results/$test

# Compare with expected results
cmp --silent $(dirname $0)/expected_results/$test actual_results/$test
