#!/bin/sh
description="passing a non-existent log file should be an error"

if [ $1 == 'describe' ]
then echo -n $description
exit
fi

test=$(basename $0)

$1 random_jklfe67ql random_pmfwds > actual_results/$test

# Compare with expected results
cmp --silent $(dirname $0)/expected_results/$test actual_results/$test
