#!/bin/sh

test=test016

echo -n "extract HTTP request line and check HTTP method stored in database......"
touch actual_results/$test.sqlite
$1 source_data/$test actual_results/$test.sqlite
echo "select http_method from stage_hits;" | sqlite3 actual_results/$test.sqlite > actual_results/$test

# Compare with expected results
cmp --silent expected_results/$test actual_results/$test

if [ $? = 0 ]; then
	rm actual_results/$test.sqlite
	exit 0
else
	exit 1
fi