#!/bin/sh
description="command line interface with no arguments should show a message"

if [ $1 == 'describe' ]
then echo -n $description
exit
fi

test=$(basename $0)

$1 > actual_results/$test

# Compare with expected results
cmp --silent $(dirname $0)/expected_results/$test actual_results/$test
