#!/bin/sh

test=$(basename $0)

echo -n "run with three parameters......"
$1 random_jklaf45 random_oue456gdsf random_qzjo731095gg > actual_results/$test

# Compare with expected results
cmp --silent $(dirname $0)/expected_results/$test actual_results/$test
