#!/bin/sh
description="a CLF entry with a full representation IPv6 address should have the IPv6 address stored correctly"

if [ $1 == 'describe' ]
then echo -n $description
exit
fi

test=$(basename $0)
test_source_dir=$(dirname $0)

echo -n "......"
echo "create table test (test int);" | sqlite3 actual_results/$test.sqlite
echo "drop table test;" | sqlite3 actual_results/$test.sqlite
echo "drop table if exists stage_hits;" | sqlite3 actual_results/$test.sqlite
$1 $test_source_dir/source_data/$test actual_results/$test.sqlite
echo "select ip_address from stage_hits;" | sqlite3 actual_results/$test.sqlite > actual_results/$test

# Compare with expected results
cmp --silent $test_source_dir/expected_results/$test actual_results/$test

if [ $? = 0 ]; then
	rm actual_results/$test.sqlite
	exit 0
else
	exit 1
fi
