#!/bin/sh
description="given a database table already exists then creating it again should be an error"

if [ $1 == 'describe' ]
then echo -n $description
exit
fi

test=$(basename $0)
test_source_dir=$(dirname $0)

$1 $test_source_dir/source_data/sample_log_file $test_source_dir/source_data/test006.sqlite > actual_results/$test

# Compare with expected results
cmp --silent $(dirname $0)/expected_results/$test actual_results/$test
