#!/bin/sh

test=test005

echo -n "attempt to open an unreadable database file......"

# Remove read access from file
chmod -r source_data/$test.sqlite

$1 source_data/sample_log_file source_data/$test.sqlite > actual_results/$test

chmod +r source_data/$test.sqlite

# Compare with expected results
cmp --silent expected_results/$test actual_results/$test
