#!/bin/sh

test=$(basename $0)

echo -n "attempt to open non-existent web log file......"
$1 random_jklfe67ql random_pmfwds > actual_results/$test

# Compare with expected results
cmp --silent $(dirname $0)/expected_results/$test actual_results/$test
