#!/bin/sh
description="a CLF entry with an empty HTTP authenticated user name should have an empty HTTP authenticated name stored"

if [ $1 == 'describe' ]
then echo -n $description
exit
fi

test=$(basename $0)
test_source_dir=$(dirname $0)

echo -n "extract empty HTTP authenticated user name field and check stored in database......"
touch actual_results/$test.sqlite
$1 $test_source_dir/source_data/$test actual_results/$test.sqlite
echo "select http_authenticated_name from stage_hits;" | sqlite3 actual_results/$test.sqlite > actual_results/$test

# Compare with expected results
cmp --silent $test_source_dir/expected_results/$test actual_results/$test

if [ $? = 0 ]; then
	rm actual_results/$test.sqlite
	exit 0
else
	exit 1
fi
