#!/bin/sh

test=$(basename $0)
test_source_dir=$(dirname $0)

echo -n "attempt to open an unreadable database file......"

# Remove read access from file
chmod -r $test_source_dir/source_data/$test.sqlite

test_build_dir=$PWD
cd $test_source_dir
$1 source_data/sample_log_file source_data/$test.sqlite > $test_build_dir/actual_results/$test
cd $test_build_dir

chmod +r $test_source_dir/source_data/$test.sqlite

# Compare with expected results
cmp --silent $test_source_dir/expected_results/$test actual_results/$test
