#!/bin/sh
description="command line interface with only one argument should be an error"

if [ $1 == 'describe' ]
then echo -n $description
exit
fi

test=$(basename $0)

$1 random_jklaf45 > actual_results/$test

# Compare with expected results
cmp --silent $(dirname $0)/expected_results/$test actual_results/$test
