#!/bin/sh

test=$(basename $0)
test_source_dir=$(dirname $0)

echo -n "extract referring URI host and check stored in database......"
touch actual_results/$test.sqlite
$1 $test_source_dir/source_data/$test actual_results/$test.sqlite
echo "select referring_host from stage_hits;" | sqlite3 actual_results/$test.sqlite > actual_results/$test

# Compare with expected results
cmp --silent $test_source_dir/expected_results/$test actual_results/$test

if [ $? = 0 ]; then
	rm actual_results/$test.sqlite
	exit 0
else
	exit 1
fi
