#!/bin/sh
description="command line interface with three arguments should be an error"

if [ $1 == 'describe' ]
then echo -n $description
exit
fi

test=$(basename $0)

$1 random_jklaf45 random_oue456gdsf random_qzjo731095gg > actual_results/$test

# Compare with expected results
cmp --silent $(dirname $0)/expected_results/$test actual_results/$test
