#!/bin/sh

test=$(basename $0)

echo -n "run with one parameter......"
$1 random_jklaf45 > actual_results/$test

# Compare with expected results
cmp --silent $(dirname $0)/expected_results/$test actual_results/$test
