#!/bin/sh

test=test003

echo -n "run with three parameters......"
$1 random_jklaf45 random_oue456gdsf random_qzjo731095gg > actual_results/$test

# Compare with expected results
cmp --silent expected_results/$test actual_results/$test
